source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.0.8"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem 'jsonapi-serializer', "~> 2.2"
gem "http", "~> 5.1"
gem "semantic_logger", "~> 4.13"
gem "faker", require: false

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.2"
end

group :test do
  gem "database_cleaner", "~> 2.0"
  gem "webmock"
end
