source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.0.8"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem 'jsonapi-serializer', "~> 2.2"
gem "http", "~> 5.1"
gem "semantic_logger", "~> 4.13"

gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end


